import React from "react";
import Carusel from "./Carusel";

import "./cardList.scss";

const data = [
  {
    title: "dfg",
    data2: [
      {
        nom: "https://www.loreal-paris.fr/dw/image/v2/BHHX_PRD/on/demandware.static/-/Sites-oap-fr-ng-Library/default/dw7cba0f40/images/landing-page/offress-peciales/Exclusive-offer-pages-4_DESK-opt.jpg?sw=1998&sh=1126&sm=cut&q=70",
        produit1: "produit1",
        produit2: "produit2",
        produit3: "produit3",
        produit4: "produit4",
        produit5: "produit5",
        produit6: "produit6",
        produit7: "produit7",
        produit8: "produit8",
        produit9: "produit9",
        produit10: "produit10",
      },
      {
        nom: "https://www.loreal-paris.fr/dw/image/v2/BHHX_PRD/on/demandware.static/-/Sites-oap-fr-ng-Library/default/dw7cba0f40/images/landing-page/offress-peciales/Exclusive-offer-pages-4_DESK-opt.jpg?sw=1998&sh=1126&sm=cut&q=70",
        produit1: "produit1",
        produit2: "produit2",
        produit3: "produit3",
        produit4: "produit4",
        produit5: "produit5",
        produit6: "produit6",
        produit7: "produit7",
        produit8: "produit8",
        produit9: "produit9",
        produit10: "produit10",
      },
      {
        nom: "https://www.loreal-paris.fr/dw/image/v2/BHHX_PRD/on/demandware.static/-/Sites-oap-fr-ng-Library/default/dw7cba0f40/images/landing-page/offress-peciales/Exclusive-offer-pages-4_DESK-opt.jpg?sw=1998&sh=1126&sm=cut&q=70",
        produit1: "produit1",
        produit2: "produit2",
        produit3: "produit3",
        produit4: "produit4",
        produit5: "produit5",
        produit6: "produit6",
        produit7: "produit7",
        produit8: "produit8",
        produit9: "produit9",
        produit10: "produit10",
      },
      {
        nom: "https://www.loreal-paris.fr/dw/image/v2/BHHX_PRD/on/demandware.static/-/Sites-oap-fr-ng-Library/default/dw7cba0f40/images/landing-page/offress-peciales/Exclusive-offer-pages-4_DESK-opt.jpg?sw=1998&sh=1126&sm=cut&q=70",
        produit1: "produit1",
        produit2: "produit2",
        produit3: "produit3",
        produit4: "produit4",
        produit5: "produit5",
        produit6: "produit6",
        produit7: "produit7",
        produit8: "produit8",
        produit9: "produit9",
        produit10: "produit10",
      },
    ],
  },
  {
    title: "dfghjg,n",

    data2: [
      {
        nom: "https://www.loreal-paris.fr/dw/image/v2/BHHX_PRD/on/demandware.static/-/Sites-oap-fr-ng-Library/default/dw7cba0f40/images/landing-page/offress-peciales/Exclusive-offer-pages-4_DESK-opt.jpg?sw=1998&sh=1126&sm=cut&q=70",
        produit1: "produit1",
        produit2: "produit2",
        produit3: "produit3",
        produit4: "produit4",
        produit5: "produit5",
        produit6: "produit6",
        produit7: "produit7",
        produit8: "produit8",
        produit9: "produit9",
        produit10: "produit10",
      },
      {
        nom: "https://www.loreal-paris.fr/dw/image/v2/BHHX_PRD/on/demandware.static/-/Sites-oap-fr-ng-Library/default/dw7cba0f40/images/landing-page/offress-peciales/Exclusive-offer-pages-4_DESK-opt.jpg?sw=1998&sh=1126&sm=cut&q=70",
        produit1: "produit1",
        produit2: "produit2",
        produit3: "produit3",
        produit4: "produit4",
        produit5: "produit5",
        produit6: "produit6",
        produit7: "produit7",
        produit8: "produit8",
        produit9: "produit9",
        produit10: "produit10",
      },
      {
        nom: "https://www.loreal-paris.fr/dw/image/v2/BHHX_PRD/on/demandware.static/-/Sites-oap-fr-ng-Library/default/dw7cba0f40/images/landing-page/offress-peciales/Exclusive-offer-pages-4_DESK-opt.jpg?sw=1998&sh=1126&sm=cut&q=70",
        produit1: "produit1",
        produit2: "produit2",
        produit3: "produit3",
        produit4: "produit4",
        produit5: "produit5",
        produit6: "produit6",
        produit7: "produit7",
        produit8: "produit8",
        produit9: "produit9",
        produit10: "produit10",
      },
      {
        nom: "https://www.loreal-paris.fr/dw/image/v2/BHHX_PRD/on/demandware.static/-/Sites-oap-fr-ng-Library/default/dw7cba0f40/images/landing-page/offress-peciales/Exclusive-offer-pages-4_DESK-opt.jpg?sw=1998&sh=1126&sm=cut&q=70",
        produit1: "produit1",
        produit2: "produit2",
        produit3: "produit3",
        produit4: "produit4",
        produit5: "produit5",
        produit6: "produit6",
        produit7: "produit7",
        produit8: "produit8",
        produit9: "produit9",
        produit10: "produit10",
      },
    ],
  },
  {
    title: "dfghgdngh",

    data2: [
      {
        nom: "https://www.loreal-paris.fr/dw/image/v2/BHHX_PRD/on/demandware.static/-/Sites-oap-fr-ng-Library/default/dw7cba0f40/images/landing-page/offress-peciales/Exclusive-offer-pages-4_DESK-opt.jpg?sw=1998&sh=1126&sm=cut&q=70",
        produit1: "produit1",
        produit2: "produit2",
        produit3: "produit3",
        produit4: "produit4",
        produit5: "produit5",
        produit6: "produit6",
        produit7: "produit7",
        produit8: "produit8",
        produit9: "produit9",
        produit10: "produit10",
      },
      {
        nom: "https://www.loreal-paris.fr/dw/image/v2/BHHX_PRD/on/demandware.static/-/Sites-oap-fr-ng-Library/default/dw7cba0f40/images/landing-page/offress-peciales/Exclusive-offer-pages-4_DESK-opt.jpg?sw=1998&sh=1126&sm=cut&q=70",
        produit1: "produit1",
        produit2: "produit2",
        produit3: "produit3",
        produit4: "produit4",
        produit5: "produit5",
        produit6: "produit6",
        produit7: "produit7",
        produit8: "produit8",
        produit9: "produit9",
        produit10: "produit10",
      },
      {
        nom: "https://www.loreal-paris.fr/dw/image/v2/BHHX_PRD/on/demandware.static/-/Sites-oap-fr-ng-Library/default/dw7cba0f40/images/landing-page/offress-peciales/Exclusive-offer-pages-4_DESK-opt.jpg?sw=1998&sh=1126&sm=cut&q=70",
        produit1: "produit1",
        produit2: "produit2",
        produit3: "produit3",
        produit4: "produit4",
        produit5: "produit5",
        produit6: "produit6",
        produit7: "produit7",
        produit8: "produit8",
        produit9: "produit9",
        produit10: "produit10",
      },
      {
        nom: "https://www.loreal-paris.fr/dw/image/v2/BHHX_PRD/on/demandware.static/-/Sites-oap-fr-ng-Library/default/dw7cba0f40/images/landing-page/offress-peciales/Exclusive-offer-pages-4_DESK-opt.jpg?sw=1998&sh=1126&sm=cut&q=70",
        produit1: "produit1",
        produit2: "produit2",
        produit3: "produit3",
        produit4: "produit4",
        produit5: "produit5",
        produit6: "produit6",
        produit7: "produit7",
        produit8: "produit8",
        produit9: "produit9",
        produit10: "produit10",
      },
    ],
  },
  {
    title: "ddjnfgfg",

    data2: [
      {
        nom: "https://www.loreal-paris.fr/dw/image/v2/BHHX_PRD/on/demandware.static/-/Sites-oap-fr-ng-Library/default/dw7cba0f40/images/landing-page/offress-peciales/Exclusive-offer-pages-4_DESK-opt.jpg?sw=1998&sh=1126&sm=cut&q=70",
        produit1: "produit1",
        produit2: "produit2",
        produit3: "produit3",
        produit4: "produit4",
        produit5: "produit5",
        produit6: "produit6",
        produit7: "produit7",
        produit8: "produit8",
        produit9: "produit9",
        produit10: "produit10",
      },
      {
        nom: "https://www.loreal-paris.fr/dw/image/v2/BHHX_PRD/on/demandware.static/-/Sites-oap-fr-ng-Library/default/dw7cba0f40/images/landing-page/offress-peciales/Exclusive-offer-pages-4_DESK-opt.jpg?sw=1998&sh=1126&sm=cut&q=70",
        produit1: "produit1",
        produit2: "produit2",
        produit3: "produit3",
        produit4: "produit4",
        produit5: "produit5",
        produit6: "produit6",
        produit7: "produit7",
        produit8: "produit8",
        produit9: "produit9",
        produit10: "produit10",
      },
      {
        nom: "https://www.loreal-paris.fr/dw/image/v2/BHHX_PRD/on/demandware.static/-/Sites-oap-fr-ng-Library/default/dw7cba0f40/images/landing-page/offress-peciales/Exclusive-offer-pages-4_DESK-opt.jpg?sw=1998&sh=1126&sm=cut&q=70",
        produit1: "produit1",
        produit2: "produit2",
        produit3: "produit3",
        produit4: "produit4",
        produit5: "produit5",
        produit6: "produit6",
        produit7: "produit7",
        produit8: "produit8",
        produit9: "produit9",
        produit10: "produit10",
      },
      {
        nom: "https://www.loreal-paris.fr/dw/image/v2/BHHX_PRD/on/demandware.static/-/Sites-oap-fr-ng-Library/default/dw7cba0f40/images/landing-page/offress-peciales/Exclusive-offer-pages-4_DESK-opt.jpg?sw=1998&sh=1126&sm=cut&q=70",
        produit1: "produit1",
        produit2: "produit2",
        produit3: "produit3",
        produit4: "produit4",
        produit5: "produit5",
        produit6: "produit6",
        produit7: "produit7",
        produit8: "produit8",
        produit9: "produit9",
        produit10: "produit10",
      },
    ],
  },
  {
    title: "dfghytydn",

    data2: [
      {
        nom: "https://www.loreal-paris.fr/dw/image/v2/BHHX_PRD/on/demandware.static/-/Sites-oap-fr-ng-Library/default/dw7cba0f40/images/landing-page/offress-peciales/Exclusive-offer-pages-4_DESK-opt.jpg?sw=1998&sh=1126&sm=cut&q=70",
        produit1: "produit1",
        produit2: "produit2",
        produit3: "produit3",
        produit4: "produit4",
        produit5: "produit5",
        produit6: "produit6",
        produit7: "produit7",
        produit8: "produit8",
        produit9: "produit9",
        produit10: "produit10",
      },
      {
        nom: "https://www.loreal-paris.fr/dw/image/v2/BHHX_PRD/on/demandware.static/-/Sites-oap-fr-ng-Library/default/dw7cba0f40/images/landing-page/offress-peciales/Exclusive-offer-pages-4_DESK-opt.jpg?sw=1998&sh=1126&sm=cut&q=70",
        produit1: "produit1",
        produit2: "produit2",
        produit3: "produit3",
        produit4: "produit4",
        produit5: "produit5",
        produit6: "produit6",
        produit7: "produit7",
        produit8: "produit8",
        produit9: "produit9",
        produit10: "produit10",
      },
      {
        nom: "https://www.loreal-paris.fr/dw/image/v2/BHHX_PRD/on/demandware.static/-/Sites-oap-fr-ng-Library/default/dw7cba0f40/images/landing-page/offress-peciales/Exclusive-offer-pages-4_DESK-opt.jpg?sw=1998&sh=1126&sm=cut&q=70",
        produit1: "produit1",
        produit2: "produit2",
        produit3: "produit3",
        produit4: "produit4",
        produit5: "produit5",
        produit6: "produit6",
        produit7: "produit7",
        produit8: "produit8",
        produit9: "produit9",
        produit10: "produit10",
      },
      {
        nom: "https://www.loreal-paris.fr/dw/image/v2/BHHX_PRD/on/demandware.static/-/Sites-oap-fr-ng-Library/default/dw7cba0f40/images/landing-page/offress-peciales/Exclusive-offer-pages-4_DESK-opt.jpg?sw=1998&sh=1126&sm=cut&q=70",
        produit1: "produit1",
        produit2: "produit2",
        produit3: "produit3",
        produit4: "produit4",
        produit5: "produit5",
        produit6: "produit6",
        produit7: "produit7",
        produit8: "produit8",
        produit9: "produit9",
        produit10: "produit10",
      },
    ],
  },
  {
    title: "dfrtshbxg",

    data2: [
      {
        nom: "https://www.loreal-paris.fr/dw/image/v2/BHHX_PRD/on/demandware.static/-/Sites-oap-fr-ng-Library/default/dw7cba0f40/images/landing-page/offress-peciales/Exclusive-offer-pages-4_DESK-opt.jpg?sw=1998&sh=1126&sm=cut&q=70",
        produit1: "produit1",
        produit2: "produit2",
        produit3: "produit3",
        produit4: "produit4",
        produit5: "produit5",
        produit6: "produit6",
        produit7: "produit7",
        produit8: "produit8",
        produit9: "produit9",
        produit10: "produit10",
      },
      {
        nom: "https://www.loreal-paris.fr/dw/image/v2/BHHX_PRD/on/demandware.static/-/Sites-oap-fr-ng-Library/default/dw7cba0f40/images/landing-page/offress-peciales/Exclusive-offer-pages-4_DESK-opt.jpg?sw=1998&sh=1126&sm=cut&q=70",
        produit1: "produit1",
        produit2: "produit2",
        produit3: "produit3",
        produit4: "produit4",
        produit5: "produit5",
        produit6: "produit6",
        produit7: "produit7",
        produit8: "produit8",
        produit9: "produit9",
        produit10: "produit10",
      },
      {
        nom: "https://www.loreal-paris.fr/dw/image/v2/BHHX_PRD/on/demandware.static/-/Sites-oap-fr-ng-Library/default/dw7cba0f40/images/landing-page/offress-peciales/Exclusive-offer-pages-4_DESK-opt.jpg?sw=1998&sh=1126&sm=cut&q=70",
        produit1: "produit1",
        produit2: "produit2",
        produit3: "produit3",
        produit4: "produit4",
        produit5: "produit5",
        produit6: "produit6",
        produit7: "produit7",
        produit8: "produit8",
        produit9: "produit9",
        produit10: "produit10",
      },
      {
        nom: "https://www.loreal-paris.fr/dw/image/v2/BHHX_PRD/on/demandware.static/-/Sites-oap-fr-ng-Library/default/dw7cba0f40/images/landing-page/offress-peciales/Exclusive-offer-pages-4_DESK-opt.jpg?sw=1998&sh=1126&sm=cut&q=70",
        produit1: "produit1",
        produit2: "produit2",
        produit3: "produit3",
        produit4: "produit4",
        produit5: "produit5",
        produit6: "produit6",
        produit7: "produit7",
        produit8: "produit8",
        produit9: "produit9",
        produit10: "produit10",
      },
    ],
  },
  {
    title: "dfxhdfcvgng",

    data2: [
      {
        nom: "https://www.loreal-paris.fr/dw/image/v2/BHHX_PRD/on/demandware.static/-/Sites-oap-fr-ng-Library/default/dw7cba0f40/images/landing-page/offress-peciales/Exclusive-offer-pages-4_DESK-opt.jpg?sw=1998&sh=1126&sm=cut&q=70",
        produit1: "produit1",
        produit2: "produit2",
        produit3: "produit3",
        produit4: "produit4",
        produit5: "produit5",
        produit6: "produit6",
        produit7: "produit7",
        produit8: "produit8",
        produit9: "produit9",
        produit10: "produit10",
      },
      {
        nom: "https://www.loreal-paris.fr/dw/image/v2/BHHX_PRD/on/demandware.static/-/Sites-oap-fr-ng-Library/default/dw7cba0f40/images/landing-page/offress-peciales/Exclusive-offer-pages-4_DESK-opt.jpg?sw=1998&sh=1126&sm=cut&q=70",
        produit1: "produit1",
        produit2: "produit2",
        produit3: "produit3",
        produit4: "produit4",
        produit5: "produit5",
        produit6: "produit6",
        produit7: "produit7",
        produit8: "produit8",
        produit9: "produit9",
        produit10: "produit10",
      },
      {
        nom: "https://www.loreal-paris.fr/dw/image/v2/BHHX_PRD/on/demandware.static/-/Sites-oap-fr-ng-Library/default/dw7cba0f40/images/landing-page/offress-peciales/Exclusive-offer-pages-4_DESK-opt.jpg?sw=1998&sh=1126&sm=cut&q=70",
        produit1: "produit1",
        produit2: "produit2",
        produit3: "produit3",
        produit4: "produit4",
        produit5: "produit5",
        produit6: "produit6",
        produit7: "produit7",
        produit8: "produit8",
        produit9: "produit9",
        produit10: "produit10",
      },
      {
        nom: "https://www.loreal-paris.fr/dw/image/v2/BHHX_PRD/on/demandware.static/-/Sites-oap-fr-ng-Library/default/dw7cba0f40/images/landing-page/offress-peciales/Exclusive-offer-pages-4_DESK-opt.jpg?sw=1998&sh=1126&sm=cut&q=70",
        produit1: "produit1",
        produit2: "produit2",
        produit3: "produit3",
        produit4: "produit4",
        produit5: "produit5",
        produit6: "produit6",
        produit7: "produit7",
        produit8: "produit8",
        produit9: "produit9",
        produit10: "produit10",
      },
    ],
  },
];
function CardsList() {
  return (
    <div className="cardsList">
      {data.map((item) => (
        <div key={item.title} style={{ width: "20%" }}>
          <h1>{item.title}</h1>
          <Carusel item={item.data2} />
        </div>
      ))}
    </div>
  );
}

export default CardsList;
