/*eslint-disable*/
export const brandOptions = [
  "L'Oréal",
  "Garnier",
  "Maybelline",
  "Nyx",
  "Essie",
  "Dark an Lovely",
  "mq",
  "Lancôme",
  "Yves Saint Laurent",
  "Giorgio Armani",
  "Kiehl's",
  "Urban Decay",
  "Biotherm",
  "Ralph Lauren",
  "Shu Uemura",
  "Clarisonic",
  "Viktor&Rolf",
  "Diesel",
  "HR",
  "Cacharel",
  "It Cosmetics",
  "Yuesai",
  "La Roche-Posay",
  "Vichy",
  "SkinCeuticals",
  "Roger&Gallet",
  "The Body Shop",
];
export const categoriesOptions = [
  "Shampoo",
  "Skin Care",
  "Hair Care",
  "Make Up",
];
